from enum import Enum


class GoodTaxSystem(Enum):
    TAX_SYSTEM_SAME_AS_GROUP = "TAX_SYSTEM_SAME_AS_GROUP"
    GENERAL_TAX_SYSTEM = "GENERAL_TAX_SYSTEM"
    SIMPLIFIED_TAX_SYSTEM_INCOME = "SIMPLIFIED_TAX_SYSTEM_INCOME"
    SIMPLIFIED_TAX_SYSTEM_INCOME_OUTCOME = "SIMPLIFIED_TAX_SYSTEM_INCOME_OUTCOME"
    UNIFIED_AGRICULTURAL_TAX = "UNIFIED_AGRICULTURAL_TAX"
    PRESUMPTIVE_TAX_SYSTEM = "PRESUMPTIVE_TAX_SYSTEM"
    PATENT_BASED = "PATENT_BASED"
